---
- name: Fetch CyberArk Privileged Access Logs
  hosts: localhost
  vars:
    pvwa_url: "https://pvwa.cybermark.lab"
    api_username: "monitoring-user"
    api_password: "yourpassword"
    start_date: "2025-06-01T00:00:00Z"
    end_date: "2025-06-17T23:59:59Z"

  tasks:
    - name: Authenticate to CyberArk
      uri:
        url: "{{ pvwa_url }}/PasswordVault/API/Auth/CyberArk/Logon"
        method: POST
        body_format: json
        body:
          username: "{{ api_username }}"
          password: "{{ api_password }}"
        return_content: yes
        status_code: 200
      register: auth_response

    - set_fact:
        token: "{{ auth_response.json.CyberArkLogonResult }}"

    - name: Retrieve usage logs
      uri:
        url: "{{ pvwa_url }}/PasswordVault/API/PrivilegedAccountUsageLogs?startDate={{ start_date }}&endDate={{ end_date }}"
        headers:
          Authorization: "Bearer {{ token }}"
        method: GET
        return_content: yes
      register: logs_response

    - name: Save logs to file
      copy:
        content: "{{ logs_response.content }}"
        dest: "./privileged_usage_logs.json"
